import { notFound } from 'next/navigation';
import { getShipment } from '@/actions/sales/shipments.actions';
import { formatDate, formatCurrency } from '@/lib/formatters';

export default async function ShipmentPrintPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  let shipment;
  try {
    shipment = await getShipment(id);
  } catch {
    notFound();
  }

  const sale = shipment.sale;

  return (
    <div className="p-8 max-w-[800px] mx-auto bg-white text-black min-h-screen print:p-0">
      <div className="flex justify-between items-start mb-8 border-b-2 border-black pb-4">
        <div>
          <h1 className="text-3xl font-bold uppercase tracking-tighter">Delivery Note</h1>
          <p className="text-sm">ใบส่งของ / ใบเตรียมพัสดุ</p>
        </div>
        <div className="text-right">
          <p className="font-bold">{shipment.shipmentNumber}</p>
          <p className="text-xs text-gray-500">Date: {formatDate(shipment.createdAt)}</p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-8 mb-8">
        <div>
          <h2 className="text-xs uppercase font-bold text-gray-500 mb-2">Ship To / ผู้รับ</h2>
          <div className="border p-4 rounded-md min-h-[120px]">
            <p className="font-bold text-lg">{shipment.recipientName}</p>
            <p className="text-sm whitespace-pre-wrap">{shipment.shippingAddress}</p>
            <p className="mt-2 font-mono text-sm">Tel: {shipment.recipientPhone || '-'}</p>
          </div>
        </div>
        <div className="text-right">
          <h2 className="text-xs uppercase font-bold text-gray-500 mb-2">Order Info</h2>
          <p className="text-sm">Invoice: <span className="font-bold">{sale.invoiceNumber}</span></p>
          <p className="text-sm">Customer: {sale.customer?.name || sale.customerName || 'General'}</p>
          <div className="mt-4 p-2 border border-dashed border-gray-300 inline-block">
             <p className="text-[10px] text-gray-400 mb-1">Tracking Number</p>
             <p className="font-mono text-lg">{shipment.trackingNumber || 'PENDING'}</p>
          </div>
        </div>
      </div>

      <table className="w-full mb-8 border-collapse">
        <thead>
          <tr className="border-b-2 border-black">
            <th className="text-left py-2 text-xs uppercase font-bold">Product</th>
            <th className="text-center py-2 text-xs uppercase font-bold w-20">Qty</th>
            <th className="text-right py-2 text-xs uppercase font-bold w-32">Note</th>
          </tr>
        </thead>
        <tbody>
          {sale.items.map((item: any) => (
            <tr key={item.id} className="border-b border-gray-200">
              <td className="py-3">
                <p className="font-medium">{item.product.name}</p>
                <p className="text-[10px] text-gray-500 font-mono">{item.product.sku}</p>
              </td>
              <td className="py-3 text-center font-bold">
                {item.quantity}
              </td>
              <td className="py-3 text-right text-xs text-gray-400 italic">
                ..........
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="grid grid-cols-2 gap-8 mt-12">
        <div className="border border-gray-200 p-4 rounded h-32 flex flex-col justify-between">
          <p className="text-[10px] text-gray-400 uppercase font-bold">Sign (Sender) / ผู้ส่ง</p>
          <div className="border-b border-black w-full mb-2"></div>
        </div>
        <div className="border border-black p-4 rounded h-32 flex flex-col justify-between">
          <p className="text-[10px] text-gray-400 uppercase font-bold">Sign (Recipient) / ผู้รับ</p>
          <div className="border-b border-black w-full mb-2"></div>
        </div>
      </div>

      <div className="mt-8 text-center text-[10px] text-gray-400 italic">
        Generated by ERP-Namfon - {new Date().toLocaleString()}
      </div>

      <div className="fixed bottom-8 right-8 print:hidden">
        <button 
          onClick={() => window.print()} 
          className="bg-black text-white px-6 py-2 rounded-full font-bold shadow-lg hover:bg-gray-800 transition-all flex items-center gap-2"
        >
          🖨️ Print Now
        </button>
      </div>

      <script dangerouslySetInnerHTML={{ __html: `
        // Auto-print on load if query param present
        if (window.location.search.includes('autoprint=true')) {
          window.print();
        }
      `}} />
    </div>
  );
}
