export const AUDIT_STATUS = {
  SUCCESS: 'SUCCESS',
  DENIED: 'DENIED',
  FAILED: 'FAILED',
} as const;

export type AuditStatus = typeof AUDIT_STATUS[keyof typeof AUDIT_STATUS];

/**
 * Standardized Action Codes (ERP Rule 12.1 Taxonomy)
 */
export const AUDIT_ACTIONS = {
  // Sales
  SALE_CREATE: 'SALE_CREATE',
  SALE_UPDATE: 'SALE_UPDATE',
  SALE_CANCEL: 'SALE_CANCEL',
  SALE_PAYMENT: 'SALE_PAYMENT',
  SALE_INVOICE_GENERATE: 'SALE_INVOICE_GENERATE',
  POS_CHECKOUT: 'POS_CHECKOUT',

  // Quotation
  QUOTATION_CREATE: 'QUOTATION_CREATE',
  QUOTATION_CONFIRM: 'QUOTATION_CONFIRM',
  QUOTATION_CANCEL: 'QUOTATION_CANCEL',

  // Invoice
  INVOICE_POST: 'INVOICE_POST',
  INVOICE_CANCEL: 'INVOICE_CANCEL',

  // Payment
  PAYMENT_RECORD: 'PAYMENT_RECORD',
  PAYMENT_VOID: 'PAYMENT_VOID',

  // Voucher
  RECEIPT_VOUCHER_CREATE: 'RECEIPT_VOUCHER_CREATE',
  PAYMENT_VOUCHER_CREATE: 'PAYMENT_VOUCHER_CREATE',

  // Inventory
  STOCK_ADJUST: 'STOCK_ADJUST',
  STOCK_TRANSFER: 'STOCK_TRANSFER',
  STOCK_TRANSFER_CREATE: 'STOCK_TRANSFER_CREATE',
  STOCK_TRANSFER_COMPLETE: 'STOCK_TRANSFER_COMPLETE',
  STOCK_BULK_PROCESS: 'STOCK_BULK_PROCESS',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',

  // Logistics / Delivery
  SHIPMENT_CREATE: 'SHIPMENT_CREATE',
  SHIPMENT_UPDATE: 'SHIPMENT_UPDATE',
  SHIPMENT_STATUS: 'SHIPMENT_STATUS',
  ROUTE_PROCESS: 'ROUTE_PROCESS',
  DELIVERY_AVAILABLE: 'DELIVERY_AVAILABLE',
  DELIVERY_CANCELLED: 'DELIVERY_CANCELLED',

  // Finance / Accounting
  JOURNAL_CREATE: 'JOURNAL_CREATE',
  JOURNAL_POST: 'JOURNAL_POST',
  JOURNAL_VOID: 'JOURNAL_VOID',
  BANK_RECONCILE: 'BANK_RECONCILE',

  // Tax
  TAX_POST: 'TAX_POST',
  TAX_VOID: 'TAX_VOID',
  WHT_CERTIFICATE_ISSUE: 'WHT_CERTIFICATE_ISSUE',
  WHT_CERTIFICATE_VOID: 'WHT_CERTIFICATE_VOID',
  WHT_CODE_UPSERT: 'WHT_CODE_UPSERT',
  WHT_CODE_TOGGLE: 'WHT_CODE_TOGGLE',
  WHT_CODE_DELETE: 'WHT_CODE_DELETE',

  // Procurement
  ORDER_REQUEST_CREATE: 'ORDER_REQUEST_CREATE',
  ORDER_REQUEST_SUBMIT: 'ORDER_REQUEST_SUBMIT',
  PURCHASE_CONVERT_FROM_OR: 'PURCHASE_CONVERT_FROM_OR',
  PURCHASE_QUICK_ASSIGN: 'PURCHASE_QUICK_ASSIGN',

  // Shop & Settings
  SHOP_UPDATE: 'SHOP_UPDATE',
  SETTINGS_UPDATE: 'SETTINGS_UPDATE',
  USER_PROFILE_UPDATE: 'USER_PROFILE_UPDATE',

  // Security & IAM
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  IAM_REVOKE_SESSIONS: 'IAM_REVOKE_SESSIONS',
  IAM_SHOP_GENESIS: 'IAM_SHOP_GENESIS',
  IAM_PASSWORD_CHANGE: 'IAM_PASSWORD_CHANGE',
  CROSS_TENANT_ACCESS: 'CROSS_TENANT_ACCESS',
  SETTINGS_ROLES: 'SETTINGS_ROLES',
  TEAM_ROLE_UPDATE: 'TEAM_ROLE_UPDATE',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',
} as const;

export const SENSITIVE_FIELDS = new Set([
  'password', 'passwordHash', 'token', 'accessToken', 'refreshToken',
  'secret', 'privateKey', 'cookie', 'sessionToken', 'credential',
  'rawCookie', 'jwtSecret'
]);
